name = "CobbledOn"
author = "me"
version = "3.1.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "86d9374a6b8704f54c90bbaa1fb1367cf517d4a4ef6a37824bd709c2c0d878df"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
